import './globals.css';
import ConstellationBackground from './ConstellationBackground';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative min-h-screen overflow-x-hidden">
        {/* Forest green background */}
        <div className="fixed inset-0 w-screen h-screen bg-forest-green z-0" style={{ position: 'fixed', top: 0, left: 0, zIndex: 0 }} />
        {/* Constellation canvas */}
        <ConstellationBackground />
        {/* Chat interface */}
        <div className="relative z-20">
          {children}
        </div>
      </body>
    </html>
  )
}
